"""Approved sermon-profile promotion and marker-aware local retrieval."""
from __future__ import annotations

import json
import re
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

REVIEW_SCHEMA = "kairos.theology-review.v1"
PROFILE_SCHEMA = "kairos.approved-sermon-rag.v1"
SERMON_INTENT_RE = re.compile(
    r"(설교|말씀\s*(?:준비|기획|작성|초안|원고)|성경|본문|주일|예배|목사님|"
    r"구원|복음|십자가|부활|성도|교회|천국|지옥|심판|신학)"
)
WORD_RE = re.compile(r"[0-9A-Za-z가-힣]{2,}")
DOMAIN_LABELS = {
    "soteriology": "구원론",
    "hamartiology": "죄론",
    "sanctification": "성화·제자도",
    "christology": "그리스도론",
    "theological_anthropology": "인간론",
    "ecclesiology": "교회론",
    "eschatology": "종말론",
    "hermeneutics": "해석 원리",
    "sermon_structure": "설교 구조",
}
GENERATED_MARKER = "# Generated by Kairos approved-sermon RAG"


def _read_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return None


def _review_files(output_dir: str | None):
    if not output_dir:
        return []
    root = Path(output_dir).expanduser()
    if not root.is_dir():
        return []
    try:
        return sorted(
            root.rglob("*.review.json"),
            key=lambda path: path.stat().st_mtime,
        )
    except OSError:
        return []


def _latest_payload(output_dir: str | None, name: str):
    if not output_dir:
        return None
    root = Path(output_dir).expanduser()
    if not root.is_dir():
        return None
    try:
        candidates = sorted(
            root.rglob(name), key=lambda path: path.stat().st_mtime, reverse=True
        )
    except OSError:
        return None
    valid = []
    for path in candidates:
        payload = _read_json(path)
        if isinstance(payload, dict):
            valid.append((path, payload))
    if not valid:
        return None
    # Year-specific and consolidated distillations coexist. For retrieval and
    # style fingerprinting, the widest audited corpus is authoritative; mtime
    # is only a tie-breaker. This prevents a later per-year run from shrinking
    # RAG coverage from the full corpus to one subset.
    if name == "fingerprint.json":
        return max(
            valid,
            key=lambda item: (
                int(item[1].get("n_docs") or 0),
                item[0].stat().st_mtime,
            ),
        )[1]
    if name == "corpus-manifest.json":
        return max(
            valid,
            key=lambda item: (
                len(item[1].get("sermons") or []),
                item[0].stat().st_mtime,
            ),
        )[1]
    return valid[0][1]


def collect_review_claims(output_dir: str | None, statuses: set[str]):
    """Collect claims in explicit review states; the latest duplicate id wins."""
    by_id = {}
    for path in _review_files(output_dir):
        payload = _read_json(path)
        if not isinstance(payload, dict) or payload.get("schema") != REVIEW_SCHEMA:
            continue
        claims = payload.get("claims")
        if not isinstance(claims, list):
            continue
        for raw in claims:
            if not isinstance(raw, dict) or raw.get("status") not in statuses:
                continue
            claim_id = str(raw.get("id") or "").strip()
            statement = str(raw.get("claim") or "").strip()
            if not claim_id or not statement:
                continue
            by_id[claim_id] = {
                "id": claim_id,
                "domain": str(raw.get("domain") or "other"),
                "claim": statement,
                "confidence": str(raw.get("confidence") or ""),
                "evidence": [
                    str(item) for item in raw.get("evidence", [])
                    if isinstance(item, str)
                ],
                "related_sermons": [
                    str(item) for item in raw.get("related_sermons", [])
                    if isinstance(item, str)
                ],
                "review_note": str(raw.get("review_note") or ""),
                "principle_type": str(raw.get("principle_type") or ""),
                "years": [
                    int(item) for item in raw.get("years", [])
                    if isinstance(item, int) or str(item).isdigit()
                ],
                "markers": [
                    str(item) for item in raw.get("markers", [])
                    if isinstance(item, str)
                ],
                "review_path": str(path.resolve()),
                "review_updated_at": payload.get("updated_at"),
            }
    return sorted(by_id.values(), key=lambda item: (item["domain"], item["id"]))


def collect_approved_claims(output_dir: str | None):
    """Collect only current principles explicitly approved by the pastor."""
    return collect_review_claims(output_dir, {"approved"})


def collect_historical_claims(output_dir: str | None):
    """Collect source-verified past sermon statements, not current doctrine."""
    return collect_review_claims(output_dir, {"historical_verified"})


def _yaml_string(value):
    return json.dumps(str(value), ensure_ascii=False)


def _render_theology_yaml(claims):
    grouped = defaultdict(list)
    for claim in claims:
        if claim["domain"] != "sermon_structure":
            grouped[claim["domain"]].append(claim)
    lines = [
        GENERATED_MARKER,
        "# Only claims explicitly approved in Kairos review documents are included.",
        f"generated_at: {_yaml_string(datetime.now(timezone.utc).date().isoformat())}",
        "source_scope: \"2025-2026 approved sermon distillation\"",
        "",
    ]
    for domain in (
        "soteriology", "hamartiology", "sanctification", "christology",
        "theological_anthropology", "ecclesiology", "eschatology",
        "hermeneutics",
    ):
        items = grouped.get(domain, [])
        lines.append(f"{domain}:")
        if not items:
            lines.extend([
                '  position: ""',
                '  emphasis: ""',
                "  key_texts: []",
                '  notes: "승인된 항목 없음"',
                "  approved_claims: []",
                "",
            ])
            continue
        lines.append(f"  position: {_yaml_string(' '.join(item['claim'] for item in items))}")
        lines.append(
            f"  emphasis: {_yaml_string(f'목사님 승인 설교 근거 {len(items)}개 항목')}"
        )
        lines.append("  key_texts: []")
        lines.append('  notes: "카이로스 승인 검토 결과에서 자동 생성. 절대 교리 평가가 아니라 목사님의 입장 기록."')
        lines.append("  approved_claims:")
        for item in items:
            lines.append(f"    - id: {_yaml_string(item['id'])}")
            lines.append(f"      statement: {_yaml_string(item['claim'])}")
            lines.append(f"      confidence: {_yaml_string(item['confidence'])}")
            lines.append("      evidence:")
            for evidence in item["evidence"]:
                lines.append(f"        - {_yaml_string(evidence)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_pattern_yaml(claims):
    items = [claim for claim in claims if claim["domain"] == "sermon_structure"]
    lines = [
        GENERATED_MARKER,
        "# Only explicitly approved sermon-structure claims are included.",
        f"generated_at: {_yaml_string(datetime.now(timezone.utc).date().isoformat())}",
        'structure: "STP 마커 기반 S → J → W → T → L 흐름"',
        "approved_structure_claims:",
    ]
    if not items:
        lines.append("  []")
    else:
        for item in items:
            lines.append(f"  - id: {_yaml_string(item['id'])}")
            lines.append(f"    statement: {_yaml_string(item['claim'])}")
            lines.append(f"    confidence: {_yaml_string(item['confidence'])}")
    lines.extend([
        "retrieval_priority:",
        '  - "W2"',
        '  - "W2-1"',
        '  - "T3"',
        '  - "J"',
    ])
    return "\n".join(lines).rstrip() + "\n"


def _write_generated(path: Path, content: str):
    """Write generated profiles without overwriting a hand-maintained profile."""
    destination = path
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            existing = ""
        if not existing.startswith(GENERATED_MARKER):
            destination = path.with_name(path.stem + ".approved" + path.suffix)
    destination.parent.mkdir(parents=True, exist_ok=True)
    old = ""
    try:
        old = destination.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        pass
    if old != content:
        destination.write_text(content, encoding="utf-8")
    return destination


def promote_approved_reviews(workspace_dir: str | None, output_dir: str | None):
    """Promote explicit approvals to author profiles and a machine RAG profile."""
    if not workspace_dir:
        return {"approved": 0, "profile_path": None, "theology_path": None}
    workspace = Path(workspace_dir).expanduser()
    if not workspace.is_dir():
        return {"approved": 0, "profile_path": None, "theology_path": None}
    claims = collect_approved_claims(output_dir)
    historical_claims = collect_historical_claims(output_dir)
    author_dir = workspace / "authors" / "main_pastor"
    profile_path = author_dir / "approved-sermon-rag.json"
    if not claims and not historical_claims and not profile_path.exists():
        return {
            "approved": 0, "profile_path": None,
            "theology_path": None, "pattern_path": None,
        }
    author_dir.mkdir(parents=True, exist_ok=True)
    fingerprint = _latest_payload(output_dir, "fingerprint.json")
    payload = {
        "schema": PROFILE_SCHEMA,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": "Kairos theology review documents",
        "approved_count": len(claims),
        "historical_count": len(historical_claims),
        "claims": claims,
        "historical_claims": historical_claims,
        "fingerprint": fingerprint,
    }
    serialized = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    previous = _read_json(profile_path)
    comparable = dict(payload)
    comparable.pop("generated_at", None)
    if isinstance(previous, dict):
        previous = dict(previous)
        previous.pop("generated_at", None)
    if previous != comparable:
        profile_path.write_text(serialized, encoding="utf-8")

    theology_path = _write_generated(
        author_dir / "theology.yaml", _render_theology_yaml(claims)
    )
    pattern_path = _write_generated(
        author_dir / "sermon_pattern.yaml", _render_pattern_yaml(claims)
    )
    if isinstance(fingerprint, dict) and fingerprint.get("n_docs"):
        (author_dir / "sermon-fingerprint.json").write_text(
            json.dumps(fingerprint, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    return {
        "approved": len(claims),
        "historical": len(historical_claims),
        "profile_path": str(profile_path),
        "theology_path": str(theology_path),
        "pattern_path": str(pattern_path),
    }


def is_sermon_request(text: str):
    return bool(SERMON_INTENT_RE.search(text or ""))


def _terms(text: str):
    stop = {
        "설교", "기획", "작성", "준비", "해줘", "해주세요", "목사님",
        "말씀", "대한", "어떻게", "이번", "주일",
    }
    return {term.lower() for term in WORD_RE.findall(text or "") if term.lower() not in stop}


def _bigrams(text: str):
    compact = re.sub(r"[^0-9a-z가-힣]", "", (text or "").lower())
    return {compact[index:index + 2] for index in range(max(0, len(compact) - 1))}


def _score(query_terms, query_bigrams, sermon):
    title = str(sermon.get("title") or "")
    passage = str(sermon.get("passage") or "")
    summary = str(sermon.get("summary") or "")
    series = str(sermon.get("series") or "")
    score = 0.0
    for term in query_terms:
        if term in title.lower():
            score += 6
        if term in passage.lower():
            score += 8
        if term in series.lower():
            score += 4
        if term in summary.lower():
            score += 2
    haystack_bigrams = _bigrams(" ".join((title, passage, series, summary)))
    if query_bigrams and haystack_bigrams:
        score += 4 * len(query_bigrams & haystack_bigrams) / len(query_bigrams)
    return score


def _latest_manifest(output_dir: str | None):
    payload = _latest_payload(output_dir, "corpus-manifest.json")
    return payload if isinstance(payload, dict) and isinstance(
        payload.get("sermons"), list
    ) else None


def build_sermon_context(
    text: str,
    workspace_dir: str | None,
    output_dir: str | None,
    *,
    max_chars: int = 6500,
):
    """Return an injection block made only from approved claims and source evidence."""
    if not is_sermon_request(text):
        return "", 0
    promotion = promote_approved_reviews(workspace_dir, output_dir)
    if not promotion["approved"] and not promotion.get("historical"):
        return "", 0
    profile = _read_json(Path(promotion["profile_path"]))
    claims = profile.get("claims", []) if isinstance(profile, dict) else []
    historical_claims = (
        profile.get("historical_claims", []) if isinstance(profile, dict) else []
    )

    query_terms = _terms(text)
    query_bigrams = _bigrams(text)
    ranked_claims = []
    for claim in claims:
        score = len(query_terms & _terms(claim["claim"])) * 3
        score += len(query_bigrams & _bigrams(claim["claim"])) / 20
        if claim["domain"] == "sermon_structure":
            score += 2
        ranked_claims.append((score, claim))
    ranked_claims.sort(key=lambda item: (item[0], item[1]["id"]), reverse=True)
    selected_claims = [claim for score, claim in ranked_claims if score > 0][:8]
    if not selected_claims:
        selected_claims = [claim for _, claim in ranked_claims[:6]]

    lines = [
        "[목사님 승인 신학·설교 프로필 — 다른 일반론보다 우선 적용]",
        "아래 항목은 목사님이 승인한 설교 증류 결과입니다. 미승인·보류·수정 필요 항목은 포함하지 않았습니다.",
    ]
    for claim in selected_claims:
        label = DOMAIN_LABELS.get(claim["domain"], claim["domain"])
        lines.append(f"- [{claim['id']}·{label}] {claim['claim']}")

    ranked_historical = []
    for claim in historical_claims:
        score = len(query_terms & _terms(claim["claim"])) * 2
        score += len(query_bigrams & _bigrams(claim["claim"])) / 30
        if claim.get("principle_type") == "sermon_structure":
            score += 1
        ranked_historical.append((score, claim))
    ranked_historical.sort(
        key=lambda item: (item[0], item[1]["id"]), reverse=True
    )
    selected_historical = [
        claim for score, claim in ranked_historical if score > 0
    ][:6]
    if selected_historical:
        lines.extend([
            "",
            "[과거 설교 확인 근거 — 현재 확정 원칙보다 낮은 우선순위]",
            "목사님의 과거 설교 원문에서 확인된 표현입니다. 현재 원칙과 충돌하면 "
            "현재 승인 원칙과 목사님의 최신 보정을 우선합니다.",
        ])
        for claim in selected_historical:
            label = DOMAIN_LABELS.get(claim["domain"], claim["domain"])
            years = ",".join(str(year) for year in claim.get("years", []))
            year_text = f"·{years}" if years else ""
            lines.append(
                f"- [{claim['id']}·{label}{year_text}] {claim['claim']}"
            )
    fingerprint = profile.get("fingerprint") if isinstance(profile, dict) else None
    if isinstance(fingerprint, dict) and fingerprint.get("n_docs"):
        sent_words = fingerprint.get("sent_words") or {}
        punct = fingerprint.get("punct_per_1k") or {}
        para = fingerprint.get("para") or {}
        lines.extend([
            "",
            f"[{fingerprint.get('scope', '전체 설교')} 문체 지문]",
            f"- 분석 설교 {fingerprint.get('n_docs')}편, 문장 {fingerprint.get('n_sents', 0)}개",
            f"- 문장 어절 중앙값 {sent_words.get('p50', 0):.1f}, "
            f"90백분위 {sent_words.get('p90', 0):.1f}",
            f"- 물음표/느낌표 밀도 {punct.get('question', 0):.2f}/"
            f"{punct.get('exclam', 0):.2f} (1천 자당), "
            f"단락 중앙값 {para.get('sents_p50', 0):.1f}문장",
        ])

    references = []
    manifest = _latest_manifest(output_dir)
    if manifest:
        sermons = manifest.get("sermons", [])
        ranked = sorted(
            ((_score(query_terms, query_bigrams, sermon), sermon) for sermon in sermons),
            key=lambda item: (item[0], str(item[1].get("date") or "")),
            reverse=True,
        )
        selected_sermons = [(score, sermon) for score, sermon in ranked if score > 0][:5]
        if selected_sermons:
            lines.extend([
                "",
                "[2019–2026 설교 RAG 검색 근거 — 인용·복제 지시가 아니라 신학과 방향 확인용]",
            ])
        for score, sermon in selected_sermons:
            evidence = sermon.get("definition_evidence") or sermon.get("theology_evidence") or []
            best = None
            best_score = -1.0
            for item in evidence:
                excerpt = str(item.get("excerpt") or "")
                item_score = len(query_terms & _terms(excerpt))
                if str(item.get("marker") or "").startswith(("W2", "T3")):
                    item_score += 1
                if item_score > best_score:
                    best, best_score = item, item_score
            excerpt = str((best or {}).get("excerpt") or sermon.get("summary") or "")[:500]
            marker = str((best or {}).get("marker") or "요약")
            article = str(sermon.get("article") or "")
            lines.append(
                f"- {sermon.get('date', '')} 「{sermon.get('title', '')}」 "
                f"({marker}, {article}): {excerpt}"
            )
            references.append(article)

    block = "\n".join(lines)
    if len(block) > max_chars:
        block = block[:max_chars].rsplit("\n", 1)[0]
    return block, len(selected_claims) + len(selected_historical) + len(references)
